//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.05 at 09:47:06 AM CEST 
//


package hu.gov.nav.schemas.osa._1_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Invoice audit data
 * 
 * <p>Java class for AuditDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuditDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="insdate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="insCusUser" type="{http://schemas.nav.gov.hu/OSA/1.0/api}LoginType"/>
 *         &lt;element name="source" type="{http://schemas.nav.gov.hu/OSA/1.0/api}SourceType"/>
 *         &lt;element name="transactionId" type="{http://schemas.nav.gov.hu/OSA/1.0/api}EntityIdType" minOccurs="0"/>
 *         &lt;element name="index" type="{http://schemas.nav.gov.hu/OSA/1.0/api}IndexType" minOccurs="0"/>
 *         &lt;element name="originalRequestVersion" type="{http://schemas.nav.gov.hu/OSA/1.0/api}RequestVersionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuditDataType", propOrder = {
    "insdate",
    "insCusUser",
    "source",
    "transactionId",
    "index",
    "originalRequestVersion"
})
public class AuditDataType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar insdate;
    @XmlElement(required = true)
    protected String insCusUser;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected SourceType source;
    protected String transactionId;
    protected Integer index;
    @XmlElement(required = true)
    protected String originalRequestVersion;

    /**
     * Gets the value of the insdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInsdate() {
        return insdate;
    }

    /**
     * Sets the value of the insdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInsdate(XMLGregorianCalendar value) {
        this.insdate = value;
    }

    /**
     * Gets the value of the insCusUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsCusUser() {
        return insCusUser;
    }

    /**
     * Sets the value of the insCusUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsCusUser(String value) {
        this.insCusUser = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link SourceType }
     *     
     */
    public SourceType getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceType }
     *     
     */
    public void setSource(SourceType value) {
        this.source = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIndex(Integer value) {
        this.index = value;
    }

    /**
     * Gets the value of the originalRequestVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalRequestVersion() {
        return originalRequestVersion;
    }

    /**
     * Sets the value of the originalRequestVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalRequestVersion(String value) {
        this.originalRequestVersion = value;
    }

}
