//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.05 at 09:47:06 AM CEST 
//


package hu.gov.nav.schemas.osa._1_0.api;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Invoice query results
 * 
 * <p>Java class for InvoiceQueryResultListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceQueryResultListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="currentPage" type="{http://schemas.nav.gov.hu/OSA/1.0/api}PageType"/>
 *         &lt;element name="availablePage" type="{http://schemas.nav.gov.hu/OSA/1.0/api}PageType"/>
 *         &lt;element name="queryResult" type="{http://schemas.nav.gov.hu/OSA/1.0/api}InvoiceQueryResultType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceQueryResultListType", propOrder = {
    "currentPage",
    "availablePage",
    "queryResult"
})
public class InvoiceQueryResultListType {

    protected int currentPage;
    protected int availablePage;
    protected List<InvoiceQueryResultType> queryResult;

    /**
     * Gets the value of the currentPage property.
     * 
     */
    public int getCurrentPage() {
        return currentPage;
    }

    /**
     * Sets the value of the currentPage property.
     * 
     */
    public void setCurrentPage(int value) {
        this.currentPage = value;
    }

    /**
     * Gets the value of the availablePage property.
     * 
     */
    public int getAvailablePage() {
        return availablePage;
    }

    /**
     * Sets the value of the availablePage property.
     * 
     */
    public void setAvailablePage(int value) {
        this.availablePage = value;
    }

    /**
     * Gets the value of the queryResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the queryResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueryResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoiceQueryResultType }
     * 
     * 
     */
    public List<InvoiceQueryResultType> getQueryResult() {
        if (queryResult == null) {
            queryResult = new ArrayList<InvoiceQueryResultType>();
        }
        return this.queryResult;
    }

}
