//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.05 at 09:47:06 AM CEST 
//


package hu.gov.nav.schemas.osa._1_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Invoice query result
 * 
 * <p>Java class for InvoiceQueryResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceQueryResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="invoiceResult" type="{http://schemas.nav.gov.hu/OSA/1.0/api}InvoiceResultType"/>
 *         &lt;element name="invoiceDigestList" type="{http://schemas.nav.gov.hu/OSA/1.0/api}InvoiceDigestListType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceQueryResultType", propOrder = {

})
public class InvoiceQueryResultType {

    @XmlElement(required = true)
    protected InvoiceResultType invoiceResult;
    @XmlElement(required = true)
    protected InvoiceDigestListType invoiceDigestList;

    /**
     * Gets the value of the invoiceResult property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceResultType }
     *     
     */
    public InvoiceResultType getInvoiceResult() {
        return invoiceResult;
    }

    /**
     * Sets the value of the invoiceResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceResultType }
     *     
     */
    public void setInvoiceResult(InvoiceResultType value) {
        this.invoiceResult = value;
    }

    /**
     * Gets the value of the invoiceDigestList property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDigestListType }
     *     
     */
    public InvoiceDigestListType getInvoiceDigestList() {
        return invoiceDigestList;
    }

    /**
     * Sets the value of the invoiceDigestList property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDigestListType }
     *     
     */
    public void setInvoiceDigestList(InvoiceDigestListType value) {
        this.invoiceDigestList = value;
    }

}
