//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.05 at 09:47:06 AM CEST 
//


package hu.gov.nav.schemas.osa._1_0.api;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Batch invoice operations of the request
 * 
 * <p>Java class for InvoiceOperationListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceOperationListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="technicalAnnulment" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="compressedContent" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="invoiceOperation" type="{http://schemas.nav.gov.hu/OSA/1.0/api}InvoiceOperationType" maxOccurs="100"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceOperationListType", propOrder = {
    "technicalAnnulment",
    "compressedContent",
    "invoiceOperation"
})
public class InvoiceOperationListType {

    @XmlElement(defaultValue = "false")
    protected boolean technicalAnnulment;
    @XmlElement(defaultValue = "false")
    protected boolean compressedContent;
    @XmlElement(required = true)
    protected List<InvoiceOperationType> invoiceOperation;

    /**
     * Gets the value of the technicalAnnulment property.
     * 
     */
    public boolean isTechnicalAnnulment() {
        return technicalAnnulment;
    }

    /**
     * Sets the value of the technicalAnnulment property.
     * 
     */
    public void setTechnicalAnnulment(boolean value) {
        this.technicalAnnulment = value;
    }

    /**
     * Gets the value of the compressedContent property.
     * 
     */
    public boolean isCompressedContent() {
        return compressedContent;
    }

    /**
     * Sets the value of the compressedContent property.
     * 
     */
    public void setCompressedContent(boolean value) {
        this.compressedContent = value;
    }

    /**
     * Gets the value of the invoiceOperation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceOperation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoiceOperationType }
     * 
     * 
     */
    public List<InvoiceOperationType> getInvoiceOperation() {
        if (invoiceOperation == null) {
            invoiceOperation = new ArrayList<InvoiceOperationType>();
        }
        return this.invoiceOperation;
    }

}
