//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.05 at 09:47:06 AM CEST 
//


package hu.gov.nav.schemas.osa._1_0.api;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hu.gov.nav.schemas.osa._1_0.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hu.gov.nav.schemas.osa._1_0.api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryInvoiceDataRequest }
     * 
     */
    public QueryInvoiceDataRequest createQueryInvoiceDataRequest() {
        return new QueryInvoiceDataRequest();
    }

    /**
     * Create an instance of {@link BasicRequestType }
     * 
     */
    public BasicRequestType createBasicRequestType() {
        return new BasicRequestType();
    }

    /**
     * Create an instance of {@link BasicHeaderType }
     * 
     */
    public BasicHeaderType createBasicHeaderType() {
        return new BasicHeaderType();
    }

    /**
     * Create an instance of {@link UserHeaderType }
     * 
     */
    public UserHeaderType createUserHeaderType() {
        return new UserHeaderType();
    }

    /**
     * Create an instance of {@link SoftwareType }
     * 
     */
    public SoftwareType createSoftwareType() {
        return new SoftwareType();
    }

    /**
     * Create an instance of {@link InvoiceQueryType }
     * 
     */
    public InvoiceQueryType createInvoiceQueryType() {
        return new InvoiceQueryType();
    }

    /**
     * Create an instance of {@link InvoiceQueryParamsType }
     * 
     */
    public InvoiceQueryParamsType createInvoiceQueryParamsType() {
        return new InvoiceQueryParamsType();
    }

    /**
     * Create an instance of {@link ManageInvoiceRequest }
     * 
     */
    public ManageInvoiceRequest createManageInvoiceRequest() {
        return new ManageInvoiceRequest();
    }

    /**
     * Create an instance of {@link InvoiceOperationListType }
     * 
     */
    public InvoiceOperationListType createInvoiceOperationListType() {
        return new InvoiceOperationListType();
    }

    /**
     * Create an instance of {@link QueryTaxpayerRequest }
     * 
     */
    public QueryTaxpayerRequest createQueryTaxpayerRequest() {
        return new QueryTaxpayerRequest();
    }

    /**
     * Create an instance of {@link GeneralExceptionResponse }
     * 
     */
    public GeneralExceptionResponse createGeneralExceptionResponse() {
        return new GeneralExceptionResponse();
    }

    /**
     * Create an instance of {@link BasicResultType }
     * 
     */
    public BasicResultType createBasicResultType() {
        return new BasicResultType();
    }

    /**
     * Create an instance of {@link TokenExchangeResponse }
     * 
     */
    public TokenExchangeResponse createTokenExchangeResponse() {
        return new TokenExchangeResponse();
    }

    /**
     * Create an instance of {@link BasicResponseType }
     * 
     */
    public BasicResponseType createBasicResponseType() {
        return new BasicResponseType();
    }

    /**
     * Create an instance of {@link QueryInvoiceStatusResponse }
     * 
     */
    public QueryInvoiceStatusResponse createQueryInvoiceStatusResponse() {
        return new QueryInvoiceStatusResponse();
    }

    /**
     * Create an instance of {@link ProcessingResultListType }
     * 
     */
    public ProcessingResultListType createProcessingResultListType() {
        return new ProcessingResultListType();
    }

    /**
     * Create an instance of {@link TokenExchangeRequest }
     * 
     */
    public TokenExchangeRequest createTokenExchangeRequest() {
        return new TokenExchangeRequest();
    }

    /**
     * Create an instance of {@link QueryTaxpayerResponse }
     * 
     */
    public QueryTaxpayerResponse createQueryTaxpayerResponse() {
        return new QueryTaxpayerResponse();
    }

    /**
     * Create an instance of {@link TaxpayerDataType }
     * 
     */
    public TaxpayerDataType createTaxpayerDataType() {
        return new TaxpayerDataType();
    }

    /**
     * Create an instance of {@link QueryInvoiceDataResponse }
     * 
     */
    public QueryInvoiceDataResponse createQueryInvoiceDataResponse() {
        return new QueryInvoiceDataResponse();
    }

    /**
     * Create an instance of {@link InvoiceQueryResultListType }
     * 
     */
    public InvoiceQueryResultListType createInvoiceQueryResultListType() {
        return new InvoiceQueryResultListType();
    }

    /**
     * Create an instance of {@link ManageInvoiceResponse }
     * 
     */
    public ManageInvoiceResponse createManageInvoiceResponse() {
        return new ManageInvoiceResponse();
    }

    /**
     * Create an instance of {@link GeneralErrorResponse }
     * 
     */
    public GeneralErrorResponse createGeneralErrorResponse() {
        return new GeneralErrorResponse();
    }

    /**
     * Create an instance of {@link GeneralErrorResponseType }
     * 
     */
    public GeneralErrorResponseType createGeneralErrorResponseType() {
        return new GeneralErrorResponseType();
    }

    /**
     * Create an instance of {@link TechnicalValidationResultType }
     * 
     */
    public TechnicalValidationResultType createTechnicalValidationResultType() {
        return new TechnicalValidationResultType();
    }

    /**
     * Create an instance of {@link QueryInvoiceStatusRequest }
     * 
     */
    public QueryInvoiceStatusRequest createQueryInvoiceStatusRequest() {
        return new QueryInvoiceStatusRequest();
    }

    /**
     * Create an instance of {@link InvoiceQueryResultType }
     * 
     */
    public InvoiceQueryResultType createInvoiceQueryResultType() {
        return new InvoiceQueryResultType();
    }

    /**
     * Create an instance of {@link PointerType }
     * 
     */
    public PointerType createPointerType() {
        return new PointerType();
    }

    /**
     * Create an instance of {@link InvoiceDigestListType }
     * 
     */
    public InvoiceDigestListType createInvoiceDigestListType() {
        return new InvoiceDigestListType();
    }

    /**
     * Create an instance of {@link InvoiceQueryTransactionType }
     * 
     */
    public InvoiceQueryTransactionType createInvoiceQueryTransactionType() {
        return new InvoiceQueryTransactionType();
    }

    /**
     * Create an instance of {@link InvoiceDigestType }
     * 
     */
    public InvoiceDigestType createInvoiceDigestType() {
        return new InvoiceDigestType();
    }

    /**
     * Create an instance of {@link TaxpayerAddressType }
     * 
     */
    public TaxpayerAddressType createTaxpayerAddressType() {
        return new TaxpayerAddressType();
    }

    /**
     * Create an instance of {@link AuditDataType }
     * 
     */
    public AuditDataType createAuditDataType() {
        return new AuditDataType();
    }

    /**
     * Create an instance of {@link InvoiceResultType }
     * 
     */
    public InvoiceResultType createInvoiceResultType() {
        return new InvoiceResultType();
    }

    /**
     * Create an instance of {@link ProcessingResultType }
     * 
     */
    public ProcessingResultType createProcessingResultType() {
        return new ProcessingResultType();
    }

    /**
     * Create an instance of {@link BusinessValidationResultType }
     * 
     */
    public BusinessValidationResultType createBusinessValidationResultType() {
        return new BusinessValidationResultType();
    }

    /**
     * Create an instance of {@link InvoiceOperationType }
     * 
     */
    public InvoiceOperationType createInvoiceOperationType() {
        return new InvoiceOperationType();
    }

}
