//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 05:51:16 PM UTC 
//


package hu.gov.nav.schemas.osa._2_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import hu.gov.nav.schemas.osa._2_0.data.InvoiceAppearanceType;
import hu.gov.nav.schemas.osa._2_0.data.InvoiceCategoryType;
import hu.gov.nav.schemas.osa._2_0.data.PaymentMethodType;


/**
 * Additional params of the invoice query
 * 
 * <p>Java class for AdditionalQueryParamsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdditionalQueryParamsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="groupMemberTaxNumber" type="{http://schemas.nav.gov.hu/OSA/2.0/data}TaxpayerIdType" minOccurs="0"/>
 *         &lt;element name="name" type="{http://schemas.nav.gov.hu/OSA/2.0/api}QueryNameType" minOccurs="0"/>
 *         &lt;element name="invoiceCategory" type="{http://schemas.nav.gov.hu/OSA/2.0/data}InvoiceCategoryType" minOccurs="0"/>
 *         &lt;element name="paymentMethod" type="{http://schemas.nav.gov.hu/OSA/2.0/data}PaymentMethodType" minOccurs="0"/>
 *         &lt;element name="invoiceAppearance" type="{http://schemas.nav.gov.hu/OSA/2.0/data}InvoiceAppearanceType" minOccurs="0"/>
 *         &lt;element name="source" type="{http://schemas.nav.gov.hu/OSA/2.0/api}SourceType" minOccurs="0"/>
 *         &lt;element name="currency" type="{http://schemas.nav.gov.hu/OSA/2.0/data}CurrencyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditionalQueryParamsType", propOrder = {
    "groupMemberTaxNumber",
    "name",
    "invoiceCategory",
    "paymentMethod",
    "invoiceAppearance",
    "source",
    "currency"
})
public class AdditionalQueryParamsType {

    protected String groupMemberTaxNumber;
    protected String name;
    @XmlSchemaType(name = "string")
    protected InvoiceCategoryType invoiceCategory;
    @XmlSchemaType(name = "string")
    protected PaymentMethodType paymentMethod;
    @XmlSchemaType(name = "string")
    protected InvoiceAppearanceType invoiceAppearance;
    @XmlSchemaType(name = "string")
    protected SourceType source;
    protected String currency;

    /**
     * Gets the value of the groupMemberTaxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupMemberTaxNumber() {
        return groupMemberTaxNumber;
    }

    /**
     * Sets the value of the groupMemberTaxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupMemberTaxNumber(String value) {
        this.groupMemberTaxNumber = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the invoiceCategory property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceCategoryType }
     *     
     */
    public InvoiceCategoryType getInvoiceCategory() {
        return invoiceCategory;
    }

    /**
     * Sets the value of the invoiceCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceCategoryType }
     *     
     */
    public void setInvoiceCategory(InvoiceCategoryType value) {
        this.invoiceCategory = value;
    }

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMethodType }
     *     
     */
    public PaymentMethodType getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMethodType }
     *     
     */
    public void setPaymentMethod(PaymentMethodType value) {
        this.paymentMethod = value;
    }

    /**
     * Gets the value of the invoiceAppearance property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceAppearanceType }
     *     
     */
    public InvoiceAppearanceType getInvoiceAppearance() {
        return invoiceAppearance;
    }

    /**
     * Sets the value of the invoiceAppearance property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceAppearanceType }
     *     
     */
    public void setInvoiceAppearance(InvoiceAppearanceType value) {
        this.invoiceAppearance = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link SourceType }
     *     
     */
    public SourceType getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceType }
     *     
     */
    public void setSource(SourceType value) {
        this.source = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

}
