//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 05:51:16 PM UTC 
//


package hu.gov.nav.schemas.osa._2_0.api;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hu.gov.nav.schemas.osa._2_0.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hu.gov.nav.schemas.osa._2_0.api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryInvoiceDataRequest }
     * 
     */
    public QueryInvoiceDataRequest createQueryInvoiceDataRequest() {
        return new QueryInvoiceDataRequest();
    }

    /**
     * Create an instance of {@link QueryInvoiceDataRequestType }
     * 
     */
    public QueryInvoiceDataRequestType createQueryInvoiceDataRequestType() {
        return new QueryInvoiceDataRequestType();
    }

    /**
     * Create an instance of {@link BasicRequestType }
     * 
     */
    public BasicRequestType createBasicRequestType() {
        return new BasicRequestType();
    }

    /**
     * Create an instance of {@link BasicHeaderType }
     * 
     */
    public BasicHeaderType createBasicHeaderType() {
        return new BasicHeaderType();
    }

    /**
     * Create an instance of {@link UserHeaderType }
     * 
     */
    public UserHeaderType createUserHeaderType() {
        return new UserHeaderType();
    }

    /**
     * Create an instance of {@link SoftwareType }
     * 
     */
    public SoftwareType createSoftwareType() {
        return new SoftwareType();
    }

    /**
     * Create an instance of {@link InvoiceNumberQueryType }
     * 
     */
    public InvoiceNumberQueryType createInvoiceNumberQueryType() {
        return new InvoiceNumberQueryType();
    }

    /**
     * Create an instance of {@link QueryTransactionStatusResponse }
     * 
     */
    public QueryTransactionStatusResponse createQueryTransactionStatusResponse() {
        return new QueryTransactionStatusResponse();
    }

    /**
     * Create an instance of {@link QueryTransactionStatusResponseType }
     * 
     */
    public QueryTransactionStatusResponseType createQueryTransactionStatusResponseType() {
        return new QueryTransactionStatusResponseType();
    }

    /**
     * Create an instance of {@link BasicResponseType }
     * 
     */
    public BasicResponseType createBasicResponseType() {
        return new BasicResponseType();
    }

    /**
     * Create an instance of {@link BasicResultType }
     * 
     */
    public BasicResultType createBasicResultType() {
        return new BasicResultType();
    }

    /**
     * Create an instance of {@link ProcessingResultListType }
     * 
     */
    public ProcessingResultListType createProcessingResultListType() {
        return new ProcessingResultListType();
    }

    /**
     * Create an instance of {@link QueryInvoiceCheckRequest }
     * 
     */
    public QueryInvoiceCheckRequest createQueryInvoiceCheckRequest() {
        return new QueryInvoiceCheckRequest();
    }

    /**
     * Create an instance of {@link GeneralExceptionResponse }
     * 
     */
    public GeneralExceptionResponse createGeneralExceptionResponse() {
        return new GeneralExceptionResponse();
    }

    /**
     * Create an instance of {@link TokenExchangeResponse }
     * 
     */
    public TokenExchangeResponse createTokenExchangeResponse() {
        return new TokenExchangeResponse();
    }

    /**
     * Create an instance of {@link TokenExchangeResponseType }
     * 
     */
    public TokenExchangeResponseType createTokenExchangeResponseType() {
        return new TokenExchangeResponseType();
    }

    /**
     * Create an instance of {@link TokenExchangeRequest }
     * 
     */
    public TokenExchangeRequest createTokenExchangeRequest() {
        return new TokenExchangeRequest();
    }

    /**
     * Create an instance of {@link QueryInvoiceDigestRequest }
     * 
     */
    public QueryInvoiceDigestRequest createQueryInvoiceDigestRequest() {
        return new QueryInvoiceDigestRequest();
    }

    /**
     * Create an instance of {@link QueryInvoiceDigestRequestType }
     * 
     */
    public QueryInvoiceDigestRequestType createQueryInvoiceDigestRequestType() {
        return new QueryInvoiceDigestRequestType();
    }

    /**
     * Create an instance of {@link InvoiceQueryParamsType }
     * 
     */
    public InvoiceQueryParamsType createInvoiceQueryParamsType() {
        return new InvoiceQueryParamsType();
    }

    /**
     * Create an instance of {@link ManageAnnulmentResponse }
     * 
     */
    public ManageAnnulmentResponse createManageAnnulmentResponse() {
        return new ManageAnnulmentResponse();
    }

    /**
     * Create an instance of {@link TransactionResponseType }
     * 
     */
    public TransactionResponseType createTransactionResponseType() {
        return new TransactionResponseType();
    }

    /**
     * Create an instance of {@link QueryTransactionStatusRequest }
     * 
     */
    public QueryTransactionStatusRequest createQueryTransactionStatusRequest() {
        return new QueryTransactionStatusRequest();
    }

    /**
     * Create an instance of {@link QueryTransactionStatusRequestType }
     * 
     */
    public QueryTransactionStatusRequestType createQueryTransactionStatusRequestType() {
        return new QueryTransactionStatusRequestType();
    }

    /**
     * Create an instance of {@link ManageInvoiceResponse }
     * 
     */
    public ManageInvoiceResponse createManageInvoiceResponse() {
        return new ManageInvoiceResponse();
    }

    /**
     * Create an instance of {@link QueryInvoiceDigestResponse }
     * 
     */
    public QueryInvoiceDigestResponse createQueryInvoiceDigestResponse() {
        return new QueryInvoiceDigestResponse();
    }

    /**
     * Create an instance of {@link QueryInvoiceDigestResponseType }
     * 
     */
    public QueryInvoiceDigestResponseType createQueryInvoiceDigestResponseType() {
        return new QueryInvoiceDigestResponseType();
    }

    /**
     * Create an instance of {@link InvoiceDigestResultType }
     * 
     */
    public InvoiceDigestResultType createInvoiceDigestResultType() {
        return new InvoiceDigestResultType();
    }

    /**
     * Create an instance of {@link QueryServiceMetricsRequest }
     * 
     */
    public QueryServiceMetricsRequest createQueryServiceMetricsRequest() {
        return new QueryServiceMetricsRequest();
    }

    /**
     * Create an instance of {@link ManageInvoiceRequest }
     * 
     */
    public ManageInvoiceRequest createManageInvoiceRequest() {
        return new ManageInvoiceRequest();
    }

    /**
     * Create an instance of {@link ManageInvoiceRequestType }
     * 
     */
    public ManageInvoiceRequestType createManageInvoiceRequestType() {
        return new ManageInvoiceRequestType();
    }

    /**
     * Create an instance of {@link InvoiceOperationListType }
     * 
     */
    public InvoiceOperationListType createInvoiceOperationListType() {
        return new InvoiceOperationListType();
    }

    /**
     * Create an instance of {@link QueryTaxpayerRequest }
     * 
     */
    public QueryTaxpayerRequest createQueryTaxpayerRequest() {
        return new QueryTaxpayerRequest();
    }

    /**
     * Create an instance of {@link QueryTaxpayerRequestType }
     * 
     */
    public QueryTaxpayerRequestType createQueryTaxpayerRequestType() {
        return new QueryTaxpayerRequestType();
    }

    /**
     * Create an instance of {@link QueryInvoiceCheckResponse }
     * 
     */
    public QueryInvoiceCheckResponse createQueryInvoiceCheckResponse() {
        return new QueryInvoiceCheckResponse();
    }

    /**
     * Create an instance of {@link QueryInvoiceCheckResponseType }
     * 
     */
    public QueryInvoiceCheckResponseType createQueryInvoiceCheckResponseType() {
        return new QueryInvoiceCheckResponseType();
    }

    /**
     * Create an instance of {@link QueryTaxpayerResponse }
     * 
     */
    public QueryTaxpayerResponse createQueryTaxpayerResponse() {
        return new QueryTaxpayerResponse();
    }

    /**
     * Create an instance of {@link QueryTaxpayerResponseType }
     * 
     */
    public QueryTaxpayerResponseType createQueryTaxpayerResponseType() {
        return new QueryTaxpayerResponseType();
    }

    /**
     * Create an instance of {@link TaxpayerDataType }
     * 
     */
    public TaxpayerDataType createTaxpayerDataType() {
        return new TaxpayerDataType();
    }

    /**
     * Create an instance of {@link QueryInvoiceDataResponse }
     * 
     */
    public QueryInvoiceDataResponse createQueryInvoiceDataResponse() {
        return new QueryInvoiceDataResponse();
    }

    /**
     * Create an instance of {@link QueryInvoiceDataResponseType }
     * 
     */
    public QueryInvoiceDataResponseType createQueryInvoiceDataResponseType() {
        return new QueryInvoiceDataResponseType();
    }

    /**
     * Create an instance of {@link InvoiceDataResultType }
     * 
     */
    public InvoiceDataResultType createInvoiceDataResultType() {
        return new InvoiceDataResultType();
    }

    /**
     * Create an instance of {@link QueryServiceMetricsResponse }
     * 
     */
    public QueryServiceMetricsResponse createQueryServiceMetricsResponse() {
        return new QueryServiceMetricsResponse();
    }

    /**
     * Create an instance of {@link QueryServiceMetricsResponseType }
     * 
     */
    public QueryServiceMetricsResponseType createQueryServiceMetricsResponseType() {
        return new QueryServiceMetricsResponseType();
    }

    /**
     * Create an instance of {@link ManageAnnulmentRequest }
     * 
     */
    public ManageAnnulmentRequest createManageAnnulmentRequest() {
        return new ManageAnnulmentRequest();
    }

    /**
     * Create an instance of {@link ManageAnnulmentRequestType }
     * 
     */
    public ManageAnnulmentRequestType createManageAnnulmentRequestType() {
        return new ManageAnnulmentRequestType();
    }

    /**
     * Create an instance of {@link AnnulmentOperationListType }
     * 
     */
    public AnnulmentOperationListType createAnnulmentOperationListType() {
        return new AnnulmentOperationListType();
    }

    /**
     * Create an instance of {@link GeneralErrorResponse }
     * 
     */
    public GeneralErrorResponse createGeneralErrorResponse() {
        return new GeneralErrorResponse();
    }

    /**
     * Create an instance of {@link GeneralErrorResponseType }
     * 
     */
    public GeneralErrorResponseType createGeneralErrorResponseType() {
        return new GeneralErrorResponseType();
    }

    /**
     * Create an instance of {@link TechnicalValidationResultType }
     * 
     */
    public TechnicalValidationResultType createTechnicalValidationResultType() {
        return new TechnicalValidationResultType();
    }

    /**
     * Create an instance of {@link DateTimeIntervalParamType }
     * 
     */
    public DateTimeIntervalParamType createDateTimeIntervalParamType() {
        return new DateTimeIntervalParamType();
    }

    /**
     * Create an instance of {@link OriginalInvoiceNumberQueryType }
     * 
     */
    public OriginalInvoiceNumberQueryType createOriginalInvoiceNumberQueryType() {
        return new OriginalInvoiceNumberQueryType();
    }

    /**
     * Create an instance of {@link RelationQueryMonetaryType }
     * 
     */
    public RelationQueryMonetaryType createRelationQueryMonetaryType() {
        return new RelationQueryMonetaryType();
    }

    /**
     * Create an instance of {@link AnnulmentOperationType }
     * 
     */
    public AnnulmentOperationType createAnnulmentOperationType() {
        return new AnnulmentOperationType();
    }

    /**
     * Create an instance of {@link MandatoryQueryParamsType }
     * 
     */
    public MandatoryQueryParamsType createMandatoryQueryParamsType() {
        return new MandatoryQueryParamsType();
    }

    /**
     * Create an instance of {@link AuditDataType }
     * 
     */
    public AuditDataType createAuditDataType() {
        return new AuditDataType();
    }

    /**
     * Create an instance of {@link AnnulmentDataType }
     * 
     */
    public AnnulmentDataType createAnnulmentDataType() {
        return new AnnulmentDataType();
    }

    /**
     * Create an instance of {@link BusinessValidationResultType }
     * 
     */
    public BusinessValidationResultType createBusinessValidationResultType() {
        return new BusinessValidationResultType();
    }

    /**
     * Create an instance of {@link InvoiceOperationType }
     * 
     */
    public InvoiceOperationType createInvoiceOperationType() {
        return new InvoiceOperationType();
    }

    /**
     * Create an instance of {@link PointerType }
     * 
     */
    public PointerType createPointerType() {
        return new PointerType();
    }

    /**
     * Create an instance of {@link AdditionalQueryParamsType }
     * 
     */
    public AdditionalQueryParamsType createAdditionalQueryParamsType() {
        return new AdditionalQueryParamsType();
    }

    /**
     * Create an instance of {@link RelationalQueryParamsType }
     * 
     */
    public RelationalQueryParamsType createRelationalQueryParamsType() {
        return new RelationalQueryParamsType();
    }

    /**
     * Create an instance of {@link InvoiceDigestType }
     * 
     */
    public InvoiceDigestType createInvoiceDigestType() {
        return new InvoiceDigestType();
    }

    /**
     * Create an instance of {@link RelationQueryDateType }
     * 
     */
    public RelationQueryDateType createRelationQueryDateType() {
        return new RelationQueryDateType();
    }

    /**
     * Create an instance of {@link TransactionQueryParamsType }
     * 
     */
    public TransactionQueryParamsType createTransactionQueryParamsType() {
        return new TransactionQueryParamsType();
    }

    /**
     * Create an instance of {@link DateIntervalParamType }
     * 
     */
    public DateIntervalParamType createDateIntervalParamType() {
        return new DateIntervalParamType();
    }

    /**
     * Create an instance of {@link ProcessingResultType }
     * 
     */
    public ProcessingResultType createProcessingResultType() {
        return new ProcessingResultType();
    }

}
