//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 05:51:16 PM UTC 
//


package hu.gov.nav.schemas.osa._2_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Response type of the POST /queryInvoiceData REST operation
 * 
 * <p>Java class for QueryInvoiceDataResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryInvoiceDataResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.nav.gov.hu/OSA/2.0/api}BasicResponseType">
 *       &lt;sequence>
 *         &lt;element name="invoiceDataResult" type="{http://schemas.nav.gov.hu/OSA/2.0/api}InvoiceDataResultType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryInvoiceDataResponseType", propOrder = {
    "invoiceDataResult"
})
@XmlSeeAlso({
    QueryInvoiceDataResponse.class
})
public class QueryInvoiceDataResponseType
    extends BasicResponseType
{

    protected InvoiceDataResultType invoiceDataResult;

    /**
     * Gets the value of the invoiceDataResult property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDataResultType }
     *     
     */
    public InvoiceDataResultType getInvoiceDataResult() {
        return invoiceDataResult;
    }

    /**
     * Sets the value of the invoiceDataResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDataResultType }
     *     
     */
    public void setInvoiceDataResult(InvoiceDataResultType value) {
        this.invoiceDataResult = value;
    }

}
