//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 05:51:16 PM UTC 
//


package hu.gov.nav.schemas.osa._2_0.api;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryOperatorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QueryOperatorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EQ"/>
 *     &lt;enumeration value="GT"/>
 *     &lt;enumeration value="GTE"/>
 *     &lt;enumeration value="LT"/>
 *     &lt;enumeration value="LTE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QueryOperatorType")
@XmlEnum
public enum QueryOperatorType {


    /**
     * Equals
     * 
     */
    EQ,

    /**
     * Greater than relation
     * 
     */
    GT,

    /**
     * Greater or equals relation
     * 
     */
    GTE,

    /**
     * Less than relation
     * 
     */
    LT,

    /**
     * Less or equals relation
     * 
     */
    LTE;

    public String value() {
        return name();
    }

    public static QueryOperatorType fromValue(String v) {
        return valueOf(v);
    }

}
