//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 05:51:16 PM UTC 
//


package hu.gov.nav.schemas.osa._2_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Request type of the POST /queryTransactionStatus REST operation
 * 
 * <p>Java class for QueryTransactionStatusRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryTransactionStatusRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.nav.gov.hu/OSA/2.0/api}BasicRequestType">
 *       &lt;sequence>
 *         &lt;element name="transactionId" type="{http://schemas.nav.gov.hu/OSA/2.0/api}EntityIdType"/>
 *         &lt;element name="returnOriginalRequest" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryTransactionStatusRequestType", propOrder = {
    "transactionId",
    "returnOriginalRequest"
})
@XmlSeeAlso({
    QueryTransactionStatusRequest.class
})
public class QueryTransactionStatusRequestType
    extends BasicRequestType
{

    @XmlElement(required = true)
    protected String transactionId;
    @XmlElement(defaultValue = "false")
    protected Boolean returnOriginalRequest;

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the returnOriginalRequest property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnOriginalRequest() {
        return returnOriginalRequest;
    }

    /**
     * Sets the value of the returnOriginalRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnOriginalRequest(Boolean value) {
        this.returnOriginalRequest = value;
    }

}
