//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.05 at 09:47:06 AM CEST 
//


package hu.gov.nav.schemas.osa._1_0.data;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hu.gov.nav.schemas.osa._1_0.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hu.gov.nav.schemas.osa._1_0.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link InvoiceType }
     * 
     */
    public InvoiceType createInvoiceType() {
        return new InvoiceType();
    }

    /**
     * Create an instance of {@link InvoiceExchangeType }
     * 
     */
    public InvoiceExchangeType createInvoiceExchangeType() {
        return new InvoiceExchangeType();
    }

    /**
     * Create an instance of {@link InvoiceAnnulmentType }
     * 
     */
    public InvoiceAnnulmentType createInvoiceAnnulmentType() {
        return new InvoiceAnnulmentType();
    }

    /**
     * Create an instance of {@link SupplierInfoType }
     * 
     */
    public SupplierInfoType createSupplierInfoType() {
        return new SupplierInfoType();
    }

    /**
     * Create an instance of {@link VesselType }
     * 
     */
    public VesselType createVesselType() {
        return new VesselType();
    }

    /**
     * Create an instance of {@link LineModificationReferenceType }
     * 
     */
    public LineModificationReferenceType createLineModificationReferenceType() {
        return new LineModificationReferenceType();
    }

    /**
     * Create an instance of {@link SummaryNormalType }
     * 
     */
    public SummaryNormalType createSummaryNormalType() {
        return new SummaryNormalType();
    }

    /**
     * Create an instance of {@link CustomerDeclarationType }
     * 
     */
    public CustomerDeclarationType createCustomerDeclarationType() {
        return new CustomerDeclarationType();
    }

    /**
     * Create an instance of {@link SummarySimplifiedType }
     * 
     */
    public SummarySimplifiedType createSummarySimplifiedType() {
        return new SummarySimplifiedType();
    }

    /**
     * Create an instance of {@link SimpleAddressType }
     * 
     */
    public SimpleAddressType createSimpleAddressType() {
        return new SimpleAddressType();
    }

    /**
     * Create an instance of {@link FiscalRepresentativeType }
     * 
     */
    public FiscalRepresentativeType createFiscalRepresentativeType() {
        return new FiscalRepresentativeType();
    }

    /**
     * Create an instance of {@link DiscountDataType }
     * 
     */
    public DiscountDataType createDiscountDataType() {
        return new DiscountDataType();
    }

    /**
     * Create an instance of {@link ProductCodeType }
     * 
     */
    public ProductCodeType createProductCodeType() {
        return new ProductCodeType();
    }

    /**
     * Create an instance of {@link AggregateInvoiceLineDataType }
     * 
     */
    public AggregateInvoiceLineDataType createAggregateInvoiceLineDataType() {
        return new AggregateInvoiceLineDataType();
    }

    /**
     * Create an instance of {@link ProductFeeSummaryType }
     * 
     */
    public ProductFeeSummaryType createProductFeeSummaryType() {
        return new ProductFeeSummaryType();
    }

    /**
     * Create an instance of {@link ReferencesToOtherLinesType }
     * 
     */
    public ReferencesToOtherLinesType createReferencesToOtherLinesType() {
        return new ReferencesToOtherLinesType();
    }

    /**
     * Create an instance of {@link ProductCodesType }
     * 
     */
    public ProductCodesType createProductCodesType() {
        return new ProductCodesType();
    }

    /**
     * Create an instance of {@link ProductFeeClauseType }
     * 
     */
    public ProductFeeClauseType createProductFeeClauseType() {
        return new ProductFeeClauseType();
    }

    /**
     * Create an instance of {@link SummaryType }
     * 
     */
    public SummaryType createSummaryType() {
        return new SummaryType();
    }

    /**
     * Create an instance of {@link InvoiceHeadType }
     * 
     */
    public InvoiceHeadType createInvoiceHeadType() {
        return new InvoiceHeadType();
    }

    /**
     * Create an instance of {@link PaymentEvidenceDocumentDataType }
     * 
     */
    public PaymentEvidenceDocumentDataType createPaymentEvidenceDocumentDataType() {
        return new PaymentEvidenceDocumentDataType();
    }

    /**
     * Create an instance of {@link AircraftType }
     * 
     */
    public AircraftType createAircraftType() {
        return new AircraftType();
    }

    /**
     * Create an instance of {@link SummaryByVatRateType }
     * 
     */
    public SummaryByVatRateType createSummaryByVatRateType() {
        return new SummaryByVatRateType();
    }

    /**
     * Create an instance of {@link LineAmountsNormalType }
     * 
     */
    public LineAmountsNormalType createLineAmountsNormalType() {
        return new LineAmountsNormalType();
    }

    /**
     * Create an instance of {@link InvoiceDataType }
     * 
     */
    public InvoiceDataType createInvoiceDataType() {
        return new InvoiceDataType();
    }

    /**
     * Create an instance of {@link VatRateType }
     * 
     */
    public VatRateType createVatRateType() {
        return new VatRateType();
    }

    /**
     * Create an instance of {@link ProductFeeTakeoverDataType }
     * 
     */
    public ProductFeeTakeoverDataType createProductFeeTakeoverDataType() {
        return new ProductFeeTakeoverDataType();
    }

    /**
     * Create an instance of {@link DieselOilPurchaseType }
     * 
     */
    public DieselOilPurchaseType createDieselOilPurchaseType() {
        return new DieselOilPurchaseType();
    }

    /**
     * Create an instance of {@link LinesType }
     * 
     */
    public LinesType createLinesType() {
        return new LinesType();
    }

    /**
     * Create an instance of {@link DetailedAddressType }
     * 
     */
    public DetailedAddressType createDetailedAddressType() {
        return new DetailedAddressType();
    }

    /**
     * Create an instance of {@link LineType }
     * 
     */
    public LineType createLineType() {
        return new LineType();
    }

    /**
     * Create an instance of {@link CustomerInfoType }
     * 
     */
    public CustomerInfoType createCustomerInfoType() {
        return new CustomerInfoType();
    }

    /**
     * Create an instance of {@link InvoiceReferenceType }
     * 
     */
    public InvoiceReferenceType createInvoiceReferenceType() {
        return new InvoiceReferenceType();
    }

    /**
     * Create an instance of {@link VehicleType }
     * 
     */
    public VehicleType createVehicleType() {
        return new VehicleType();
    }

    /**
     * Create an instance of {@link ProductFeeDataType }
     * 
     */
    public ProductFeeDataType createProductFeeDataType() {
        return new ProductFeeDataType();
    }

    /**
     * Create an instance of {@link EkaerIdsType }
     * 
     */
    public EkaerIdsType createEkaerIdsType() {
        return new EkaerIdsType();
    }

    /**
     * Create an instance of {@link NewTransportMeanType }
     * 
     */
    public NewTransportMeanType createNewTransportMeanType() {
        return new NewTransportMeanType();
    }

    /**
     * Create an instance of {@link LineAmountsSimplifiedType }
     * 
     */
    public LineAmountsSimplifiedType createLineAmountsSimplifiedType() {
        return new LineAmountsSimplifiedType();
    }

    /**
     * Create an instance of {@link AdditionalDataType }
     * 
     */
    public AdditionalDataType createAdditionalDataType() {
        return new AdditionalDataType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link TaxNumberType }
     * 
     */
    public TaxNumberType createTaxNumberType() {
        return new TaxNumberType();
    }

}
