//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.05 at 09:47:06 AM CEST 
//


package hu.gov.nav.schemas.osa._1_0.data;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Calculation of simplified invoice totals
 * 
 * <p>Java class for SummarySimplifiedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SummarySimplifiedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vatContent" type="{http://schemas.nav.gov.hu/OSA/1.0/data}RateType"/>
 *         &lt;element name="vatContentGrossAmount" type="{http://schemas.nav.gov.hu/OSA/1.0/data}MonetaryType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SummarySimplifiedType", propOrder = {
    "vatContent",
    "vatContentGrossAmount"
})
public class SummarySimplifiedType {

    @XmlElement(required = true)
    protected BigDecimal vatContent;
    @XmlElement(required = true)
    protected BigDecimal vatContentGrossAmount;

    /**
     * Gets the value of the vatContent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVatContent() {
        return vatContent;
    }

    /**
     * Sets the value of the vatContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVatContent(BigDecimal value) {
        this.vatContent = value;
    }

    /**
     * Gets the value of the vatContentGrossAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVatContentGrossAmount() {
        return vatContentGrossAmount;
    }

    /**
     * Sets the value of the vatContentGrossAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVatContentGrossAmount(BigDecimal value) {
        this.vatContentGrossAmount = value;
    }

}
