//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.05 at 09:47:06 AM CEST 
//


package hu.gov.nav.schemas.osa._1_0.data;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Marking tax rate or tax exempt supply
 * 
 * <p>Java class for VatRateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VatRateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="vatPercentage" type="{http://schemas.nav.gov.hu/OSA/1.0/data}RateType"/>
 *         &lt;element name="vatExemption" type="{http://schemas.nav.gov.hu/OSA/1.0/data}SimpleText50NotBlankType"/>
 *         &lt;element name="vatOutOfScope" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="vatDomesticReverseCharge" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="marginSchemeVat" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="marginSchemeNoVat" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VatRateType", propOrder = {
    "vatPercentage",
    "vatExemption",
    "vatOutOfScope",
    "vatDomesticReverseCharge",
    "marginSchemeVat",
    "marginSchemeNoVat"
})
public class VatRateType {

    protected BigDecimal vatPercentage;
    protected String vatExemption;
    @XmlElement(defaultValue = "false")
    protected Boolean vatOutOfScope;
    @XmlElement(defaultValue = "false")
    protected Boolean vatDomesticReverseCharge;
    @XmlElement(defaultValue = "false")
    protected Boolean marginSchemeVat;
    @XmlElement(defaultValue = "false")
    protected Boolean marginSchemeNoVat;

    /**
     * Gets the value of the vatPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVatPercentage() {
        return vatPercentage;
    }

    /**
     * Sets the value of the vatPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVatPercentage(BigDecimal value) {
        this.vatPercentage = value;
    }

    /**
     * Gets the value of the vatExemption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVatExemption() {
        return vatExemption;
    }

    /**
     * Sets the value of the vatExemption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVatExemption(String value) {
        this.vatExemption = value;
    }

    /**
     * Gets the value of the vatOutOfScope property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVatOutOfScope() {
        return vatOutOfScope;
    }

    /**
     * Sets the value of the vatOutOfScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVatOutOfScope(Boolean value) {
        this.vatOutOfScope = value;
    }

    /**
     * Gets the value of the vatDomesticReverseCharge property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVatDomesticReverseCharge() {
        return vatDomesticReverseCharge;
    }

    /**
     * Sets the value of the vatDomesticReverseCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVatDomesticReverseCharge(Boolean value) {
        this.vatDomesticReverseCharge = value;
    }

    /**
     * Gets the value of the marginSchemeVat property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMarginSchemeVat() {
        return marginSchemeVat;
    }

    /**
     * Sets the value of the marginSchemeVat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMarginSchemeVat(Boolean value) {
        this.marginSchemeVat = value;
    }

    /**
     * Gets the value of the marginSchemeNoVat property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMarginSchemeNoVat() {
        return marginSchemeNoVat;
    }

    /**
     * Sets the value of the marginSchemeNoVat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMarginSchemeNoVat(Boolean value) {
        this.marginSchemeNoVat = value;
    }

}
