//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 05:51:16 PM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.nav.gov.hu/OSA/2.0/data", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hu.gov.nav.schemas.osa._2_0.data;
